;# import rfc9711 as eat

get-agent-status-output = [
  + agent-status-record,
]

agent-status-record = [
  kid: bstr .size 32,
  status: agent-status,
]

agent-status = {
  attributes-label => agent-attributes,
  installed-tc-label => [ * suit-manifest-overview ],
}

attributes-label = 1
installed-tc-label = 2

agent-attributes = {
  eat.ueid-label => eat.ueid-type,
}
