;# import rfc9711 as eat

get-agent-status-output = [
  * agent-status-record,
]

agent-status-record = [
  kid: bstr .size 32,
  status: agent-status,
]

agent-status = {
  "attributes": agent-attributes,
  "wapp_list": [ * component-list ],
}

agent-attributes = {
  eat.ueid-label => eat.ueid-type,
}

component-list = [
  component: bstr .cbor SUIT_Component_Identifier,
  manifest-sequence-number: uint,
]
