;# import rfc9711 as eat
; requires SUIT Manifest CDDL and SUIT Manifest Overview CDDL

get-agent-status-output = [
  * agent-status-record,
]

agent-status-record = [
  kid: bstr .size 32,
  status: agent-status,
]

agent-status = {
  "attributes": agent-attributes,
  "wapp_list": [ * suit-manifest-overview ],
}

agent-attributes = {
  eat.ueid-label => eat.ueid-type,
}
